### ISSUE TITLE
YAML-format API is invalid

### ISSUE THREAD

**Issue by gdude2002** [StopModReposts/Illegal-Mod-Sites#266]
The format of the YAML file at https://api.varden.info/smr/sitelist.php?format=yaml is invalid. It contains
unescaped quotes in quoted strings. As an example:

```yaml
    domain: 'hackphoenix.com'
    path: '/'
    pattern: 'https?:\/\/([^\s\.]+\.)*hackphoenix\.com(\/[^\s]*)?'
    advertising: '5'
    redistribution: '5'
    miscellaneous: '5'
    notes: 'Also distributes cracked launchers, and Mojang's intellectual property'
```

Specifically: `notes: 'Also distributes cracked launchers, and Mojang's intellectual property'` contains an unescaped single quote in `Mojang's`.

As this file doesn't contain a single double-quote, I recommend switching to using double quotes for notes.

---

Alternatively, an API would probably be unnecessary if a YAML file with a top-level `sites` key was maintained within the repo itself.
